### ISSUE TITLE
Failure to build from souce

### ISSUE THREAD

**Issue by ColumPaget** [pinaraf/Slacken#14]
Compiling with 8.1.0 and Qt 5.9.1:

slackclient.cpp: In lambda function:
slackclient.cpp:88:50: error: no match for 'operator[]' (operand types are 'QJsonDocument' and 'const QString')
             for (const QJsonValueRef channel: doc[listPath].toArray()) {
                                                  ^
slackclient.cpp: In lambda function:
slackclient.cpp:112:21: error: no match for 'operator[]' (operand types are 'QJsonDocument' and 'const char [5]')
         selfId = doc["self"].toObject()["id"].toString();
                     ^
slackclient.cpp:113:25: error: no match for 'operator[]' (operand types are 'QJsonDocument' and 'const char [5]')
         m_teamName = doc["team"].toObject()["name"].toString();
                         ^
slackclient.cpp:117:43: error: no match for 'operator[]' (operand types are 'QJsonDocument' and 'const char [6]')
         for (const QJsonValueRef user: doc["users"].toArray()) {
                                           ^
slackclient.cpp:124:46: error: no match for 'operator[]' (operand types are 'QJsonDocument' and 'const char [9]')
         for (const QJsonValueRef channel: doc["channels"].toArray()) {
                                              ^
slackclient.cpp:131:46: error: no match for 'operator[]' (operand types are 'QJsonDocument' and 'const char [7]')
         for (const QJsonValueRef channel: doc["groups"].toArray()) {
                                              ^
slackclient.cpp:138:46: error: no match for 'operator[]' (operand types are 'QJsonDocument' and 'const char [4]')
         for (const QJsonValueRef channel: doc["ims"].toArray()) {

**Comment by pinaraf** [comment]
Hi

Indeed, thank you for the report. I used the [] operator, but I did not see it was available only with Qt ≥5.10.
I can't push a fix right now, will do that in one or two hours.

**Comment by pinaraf** [comment]
I've pushed a fix, could you try again please ? (I don't have a Qt 5.9 available right now for testing)

**Comment by pinaraf** [comment]
I finished the installation of Qt 5.9, and another fix was needed. I've closed the issue since it is now working. Thanks for the report again.

**Comment by ColumPaget** [comment]
Hi, it builds now. Thanks for the fix!
